---
devices:
  switch1:
    interface:
     'ae1':
        port_mode: trunk
        vlan_members:
          - VLAN_A
          - VLAN_B
    irbinf:
      '441':
        description: VLAN A
        prefix: 10.1.10.0/28
      '442':
        description: VLAN B
        prefix: 10.1.20.0/28
    vlan:
      "VLAN_A":
        vlanid: 441
        description: VLAN A
        l3vlanid: 441
      "VLAN_B":
        vlanid: 442
        description: VLAN B
        l3vlanid: 442
    routinginstance:
      'Instance_A':
         interface:
           - irb.441
           - irb.442
         ospf:
          '0.0.0.0':
            passive:
              - irb.441
              - irb.442
         pim:
          - irb.441
          - irb.442