---
# =========================================================
# Setup variables and directories
# =========================================================

- name: Creating build directories for each Device type
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: delete previous build directory
      file:
        state: absent
        path: "{{ build_dir }}"
      changed_when: no
      check_mode: no
    - name: create host build directory
      file:
        path: "{{ build_dir }}/{{ inventory_hostname }}"
        state: directory
        recurse: yes
        mode: 0755
      changed_when: no
      check_mode: no


# =========================================================
# Role based config template building - 
# =========================================================

- name: Build New Switchport Template
  hosts: junos
  connection: local
  gather_facts: no
  roles:
    - switchport